language: java
script : mvn clean verify dependency:go-offline
cache :
  directories: 
    - "$HOME/.m2/repository"
jobs:
  include:
    
    - stage: build
      script: 
        - docker login -u "$USERNAME_DOCKER" | -p "$PWD_DOCKER --password-stdin
        - docker build -t httpd sample-application-http-api-server
        - docker build -t bdd sample-application-db-changelog-job
        - docker tag httpd $do/sample-application-students:httpd
        - docker tag bdd $USERNAME_DOCKER/sample-application-students:bdd
        - docker push $USERNAME_DOCKER/sample-application-students:httpd
        - docker push $USERNAME_DOCKER/sample-application-students:bdd

stages:
  - name: build
    if: branch = master