language: java
script : mvn clean verify dependency:go-offline
cache :
  directories: 
    - "$HOME/.m2/repository"
jobs:
  include:
    
    - stage: build
      script: 
        - echo "$PWD_DOCKER" | docker login -u "$USERNAME_DOCKER" --password-stdin
        - docker build -t http sample-application-http-api-server
        - docker build -t bdd sample-application-db-changelog-job
        - docker tag http $USERNAME_DOCKER/sample-application-students:http
        - docker tag bdd $USERNAME_DOCKER/sample-application-students:bdd
        - docker push $USERNAME_DOCKER/sample-application-students:http
        - docker push $USERNAME_DOCKER/sample-application-students:bdd

stages:
  - name: build
    if: branch = dev