language: java
script : mvn clean verify dependency:go-offline
cache :
  directories: 
    - "$HOME/.m2/repository"

addons:
  sonarcloud:
    organization: "bonuccihugo"
    token:
      secure: $sonar_token
      
jobs:
  include:
    
    - stage: cloner
      script: 
        -  mvn clean verify sonar:sonar -Dsonar.projectKey=BonucciHugo_sample-application-students 
    - stage: build
      script: 
        - echo "$PWD_DOCKER" | docker login -u "$USERNAME_DOCKER" --password-stdin
        - docker build -t http sample-application-http-api-server
        - docker build -t bdd sample-application-db-changelog-job
        - docker tag http $USERNAME_DOCKER/sample-application-http-api-server:http
        - docker tag bdd $USERNAME_DOCKER/sample-application-db-changelog-job:bdd
        - docker push $USERNAME_DOCKER/sample-application-http-api-server:http
        - docker push $USERNAME_DOCKER/sample-application-db-changelog-job:bdd

stages:
  - name : cloner
  - name: build
    if: branch = master